/**
 * 侧边栏只声明一级知识域，二级及以下结构由 docs/ 目录和
 * 各目录中的 _category_.json 自动生成。
 *
 * 这样本地目录就是网站目录的唯一事实来源：移动文章后只需修正
 * Markdown 链接，无须再维护一份重复的手工文章清单。
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: '学习导航',
      className: 'sidebar-domain sidebar-domain--learning',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'learning'}],
    },
    {
      type: 'category',
      label: 'Linux 与操作系统',
      className: 'sidebar-domain sidebar-domain--linux',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'linux'}],
    },
    {
      type: 'category',
      label: 'GPU 与加速计算',
      className: 'sidebar-domain sidebar-domain--gpu',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'gpu'}],
    },
    {
      type: 'category',
      label: '网络',
      className: 'sidebar-domain sidebar-domain--network',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'networking'}],
    },
    {
      type: 'category',
      label: '存储',
      className: 'sidebar-domain sidebar-domain--storage',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'storage'}],
    },
    {
      type: 'category',
      label: '容器与 Kubernetes',
      className: 'sidebar-domain sidebar-domain--kubernetes',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'cloud-native'}],
    },
    {
      type: 'category',
      label: 'AI 训练与推理',
      className: 'sidebar-domain sidebar-domain--ai',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'ai-systems'}],
    },
    {
      type: 'category',
      label: '数据系统',
      className: 'sidebar-domain sidebar-domain--data',
      collapsed: true,
      link: {type: 'doc', id: 'data-systems/数据系统学习地图'},
      items: [{type: 'autogenerated', dirName: 'data-systems'}],
    },
    {
      type: 'category',
      label: '可观测性与 SRE',
      className: 'sidebar-domain sidebar-domain--sre',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'sre'}],
    },
    {
      type: 'category',
      label: '自动化与 DevOps',
      className: 'sidebar-domain sidebar-domain--automation',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'automation'}],
    },
    {
      type: 'category',
      label: '综合项目',
      className: 'sidebar-domain sidebar-domain--projects',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'projects'}],
    },
  ],
};

export default sidebars;
