/**
 * 侧栏以「目录结构」为主：各子目录用 _category_.json 控制中文标题与顺序。
 * 仅保留信息架构大类的标题；其下由 Docusaurus 按 docs/ 子树自动生成。
 * 说明：https://docusaurus.io/docs/sidebar/autogenerated
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: '云原生与 AI 算力',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'cloud-native-ai' }],
    },
    {
      type: 'category',
      label: '网络与硬件',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'network-hardware' }],
    },
    {
      type: 'category',
      label: '基础设施与总线',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'infrastructure' }],
    },
    {
      type: 'category',
      label: '工程笔记与排障',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'engineering' }],
    },
  ],
};

export default sidebars;
